### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by highacid** [ElDeveloper/keystats#18]
Hello,

I tried to build it and this is what I get: http://prntscr.com/9sml1b any idea? Can I have a built version .dmg file for 10.11 El capitan?

Regards,
Cosmin

**Comment by ElDeveloper** [comment]
@highacid, as it is the master branch is broken, but I would try with the open PR that I have in #17, the only reason why that branch hasn't been merged, is because I haven't quite figured out how to fix the Travis.yml error, however I'm using the app as built with that branch and it works great! I'm linking to it [here](http://cl.ly/2Z1M3p0y2h0V) just in case it is easier for you to download it, though you should be able to compile it using El Capitan (granted that you use that branch).

Let me know if this fixes your problem!
